### ISSUE TITLE
Querystringify ignores query components without values

### ISSUE THREAD

**Issue by miinx** [unshiftio/querystringify#1]
Hi there,

Querystringify ignores query components without values, e.g. in `?foo`, the returned object is empty.

Query components without values are valid according to [the spec](https://tools.ietf.org/html/rfc3986#section-3.4).

Happy to submit a PR if you agree & would like?

Cheers
Karen

**Comment by lpinca** [comment]
Yes, we have received the same request in our IRC channel some time ago.
PR is welcome, thanks.

**Comment by miinx** [comment]
Great, I'll get that to you sometime this week, thanks.

**Comment by miinx** [comment]
Hi @lpinca, sorry I forgot to come back to this until now, PR just raised though 😄
