### ISSUE TITLE
Query strings without values are interpreted as having an empty value

### ISSUE THREAD

**Issue by webark** [unshiftio/querystringify#14]
If you take the query string
```?foo&bar=other```
and parse it and then stringify it again, you will get 
```?foo=&bar=other```
this is causing us issues, cause `?foo` (for us at least) does not mean the same thing as `foo=` Is this something that you would want to change in this library? The w3 spec seems somewhat ambiguous to the differences. But just thought I'd bring the idea up.

**Comment by lpinca** [comment]
This is consistent with the Node.js [`querystring`](https://nodejs.org/dist/latest/docs/api/querystring.html) module:

```js
$ node
> querystring.parse('foo&bar=1')
{ foo: '', bar: '1' }
> querystring.stringify({ foo: '', bar: '1' })
'foo=&bar=1'
```

**Comment by webark** [comment]
ok cool. I modified the app to account for that. This is at least here for recordincase anyone else runs into the same issue. Thanks!
