### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by robbisy** [unshiftio/querystringify#15]
Hi I have a question about array.
I found this [file](https://github.com/billerickson/BE-Subpages-Widget/blob/gutenberg/blocks/list-subpages/select-subpages.js#L35-L44) and I wonder how stringify works with array. I mean when I have 
```
const query = stringify( {
		context: 'edit',
		per_page: 100,
		orderby: 'menu_order',
		order: 'asc',
		_fields: [ 'id', 'parent', 'title' ],
} );
```
I get `context=edit&per_page=100&orderby=menu_order&order=asc` but then how do it work with _fields: [ 'id', 'parent', 'title' ] ?
Thank you

**Comment by lpinca** [comment]
This module is super simple and does not have proper support for arrays. The above example will produce a comma separated string of the array values.

```js
'_fields=id%2Cparent%2Ctitle'
```

If you need proper support for arrays you need a different module, like [qs](https://github.com/ljharb/qs) for example.

**Comment by andrewmclagan** [comment]
sade face...
