### ISSUE TITLE
Array handling is inconsistent

### ISSUE THREAD

**Issue by heygrady** [unshiftio/querystringify#23]
I don't think this library needs to have any type of robust array support. But querystringify's current behavior WRT arrays seems broken.

**Problem:**
- parse `foo=a&foo=b` becomes `{ foo: 'a' }`
- stringify `{ foo: ['a', 'b'] }` becomes `foo=a,b`
- parse `foo=a,b` becomes `{ foo: 'a,b' }`

I made a comparison of what popular libraries do: https://repl.it/@heygrady/querystring-arrays

- `querystring` seems to work the way I would expect.
- `qs` offers robust array support but that's not what a user of `querystringify` would expect.
  - qs is [huge](https://bundlephobia.com/result?p=qs@6.6.0) (3.2Kb)
  - querystringify is [tiny](https://bundlephobia.com/result?p=querystringify@2.1.0) (409B)

**Expected behavior:**
- parse `foo=a&foo=b` becomes `{ foo: ['a', 'b'] }`
- stringify `{ foo: ['a', 'b'] }` becomes `foo=a&foo=b`
- parse `foo=a,b` becomes `{ foo: 'a,b' }`

Related: #15, #17

**NOTE:** I like the way the other query string parsers treat `foo[]` as a distinct key from `foo` (instead of trying to treat the brackets as an array). That dramatically simplifies things.

**Comment by lpinca** [comment]
As said in #15 this module does not have proper support for arrays.
