### ISSUE TITLE
Implement Node's safe decode alternative

### ISSUE THREAD

**Issue by niftylettuce** [unshiftio/querystringify#26]
We should try to match Node behavior in the browser, and to do so, instead of returning `null`, we'd need to implement Node's fallback:

https://github.com/nodejs/node/blob/908292cf1f551c614a733d858528ffb13fb3a524/lib/querystring.js#L397-L403 which specifically uses https://github.com/nodejs/node/blob/908292cf1f551c614a733d858528ffb13fb3a524/lib/querystring.js#L67-L108

**Comment by lpinca** [comment]
FWIW I think compatibility with Node.js `querystring` module has never been an objective. This module does not even handle arrays.
