### ISSUE TITLE
0.0.4 bug about /s?a=b

### ISSUE THREAD

**Issue by xingxp** [unshiftio/querystringify#3]
in version 0.0.4
qs.parse("/s?param1=1&param2=2")

you will get
{
"/s":"?param1=1",
param2:2
}

but in 0.0.3 it's fine

**Comment by lpinca** [comment]
Well your query string should not include the path as per this [definition](https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/search).

**Comment by lpinca** [comment]
Closing as per my previous comment.
