### ISSUE TITLE
when query value is `undefined`, it still generate string

### ISSUE THREAD

**Issue by tqma113** [unshiftio/querystringify#31]
I think the way transiform the query object to search string is not strict.
`let str = querystring({ the: undefined })`
the `str` should be `''`, but the result is `'?the='`

**Comment by senyaak** [comment]
this is correct - if u dont want to have `the` field in qs - use something like that
```js
let obj = { the: undefined };
delete obj.the;
let str = querystring(obj);
```

**Comment by tqma113** [comment]
@senyaak OK, Thanks.
